---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar", "gzip"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create backend directory for backend app"
  shell: |
    mkdir /home/ubuntu/backend
- name: "extract zipped artifact"
  unarchive:
    src: "../../artifact.tar.gz"
    dest: "/home/ubuntu/backend"


- name: "start app"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm build
    pm2 stop default
    pm2 start npm -- start
